# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pb.uploadphoto_pb2 as uploadphoto__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in uploadphoto_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PhotoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Photo = channel.unary_unary(
                '/PhotoService/Photo',
                request_serializer=uploadphoto__pb2.IdRequest.SerializeToString,
                response_deserializer=uploadphoto__pb2.PhotoResponse.FromString,
                _registered_method=True)
        self.AddPhoto = channel.unary_unary(
                '/PhotoService/AddPhoto',
                request_serializer=uploadphoto__pb2.PhotoRequest.SerializeToString,
                response_deserializer=uploadphoto__pb2.PhotoResponse.FromString,
                _registered_method=True)
        self.RandomPhotos = channel.unary_stream(
                '/PhotoService/RandomPhotos',
                request_serializer=uploadphoto__pb2.CountRequest.SerializeToString,
                response_deserializer=uploadphoto__pb2.PhotoResponse.FromString,
                _registered_method=True)
        self.UploadPhotos = channel.stream_unary(
                '/PhotoService/UploadPhotos',
                request_serializer=uploadphoto__pb2.PhotoRequest.SerializeToString,
                response_deserializer=uploadphoto__pb2.UploadStatus.FromString,
                _registered_method=True)


class PhotoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Photo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddPhoto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RandomPhotos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadPhotos(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PhotoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Photo': grpc.unary_unary_rpc_method_handler(
                    servicer.Photo,
                    request_deserializer=uploadphoto__pb2.IdRequest.FromString,
                    response_serializer=uploadphoto__pb2.PhotoResponse.SerializeToString,
            ),
            'AddPhoto': grpc.unary_unary_rpc_method_handler(
                    servicer.AddPhoto,
                    request_deserializer=uploadphoto__pb2.PhotoRequest.FromString,
                    response_serializer=uploadphoto__pb2.PhotoResponse.SerializeToString,
            ),
            'RandomPhotos': grpc.unary_stream_rpc_method_handler(
                    servicer.RandomPhotos,
                    request_deserializer=uploadphoto__pb2.CountRequest.FromString,
                    response_serializer=uploadphoto__pb2.PhotoResponse.SerializeToString,
            ),
            'UploadPhotos': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadPhotos,
                    request_deserializer=uploadphoto__pb2.PhotoRequest.FromString,
                    response_serializer=uploadphoto__pb2.UploadStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PhotoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('PhotoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PhotoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Photo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PhotoService/Photo',
            uploadphoto__pb2.IdRequest.SerializeToString,
            uploadphoto__pb2.PhotoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddPhoto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PhotoService/AddPhoto',
            uploadphoto__pb2.PhotoRequest.SerializeToString,
            uploadphoto__pb2.PhotoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RandomPhotos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/PhotoService/RandomPhotos',
            uploadphoto__pb2.CountRequest.SerializeToString,
            uploadphoto__pb2.PhotoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadPhotos(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/PhotoService/UploadPhotos',
            uploadphoto__pb2.PhotoRequest.SerializeToString,
            uploadphoto__pb2.UploadStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
